# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-17 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.TextField(max_length=140, null=True),
        ),
    ]
