# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 09:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0002_auto_20170717_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.TextField(max_length=140),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set([('followed_user', 'following_user')]),
        ),
    ]
